import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { ForTheLGeneratedModule, ForTheLGeneratedSharedModule } from './generated/module.js';
import { ForTheLValidator, registerValidationChecks } from './for-the-l-validator.js';
import { ForTheLCodeActionProvider } from './for-the-l-code-actions.js';
import { ForTheLSemanticTokenProvider } from './for-the-l-semantic-tokens.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type ForTheLAddedServices = {
    validation: {
        ForTheLValidator: ForTheLValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ForTheLServices = LangiumServices & ForTheLAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ForTheLModule: Module<ForTheLServices, PartialLangiumServices & ForTheLAddedServices> = {
    validation: {
        ForTheLValidator: () => new ForTheLValidator()
    },
    lsp: {
        CodeActionProvider: () => new ForTheLCodeActionProvider(),
        SemanticTokenProvider: (services) => new ForTheLSemanticTokenProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createForTheLServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    ForTheL: ForTheLServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        ForTheLGeneratedSharedModule
    );
    const ForTheL = inject(
        createDefaultModule({ shared }),
        ForTheLGeneratedModule,
        ForTheLModule
    );
    shared.ServiceRegistry.register(ForTheL);
    registerValidationChecks(ForTheL);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, ForTheL };
}
